name: Weather Auto Sender

on:
  schedule:
    - cron: '0 6 * * *'     # هر روز ساعت 6 صبح UTC
    - cron: '0 18 * * *'    # هر روز ساعت 6 عصر UTC
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: python send_weather.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
          CHAT_IDS: ${{ secrets.CHAT_IDS }}
          REGION_NAME: ${{ secrets.REGION_NAME }}
          IMAGE_URL: ${{ secrets.IMAGE_URL }}
